version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # Mapea el puerto 3001 del contenedor al puerto 3005 de la máquina local
    environment:
      PORT: ${PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SEED: ${JWT_SEED}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/usr/src/app # Monta el directorio actual en el contenedor
    command: ["npm", "start"]
